// Copy everything onboard
SET TERMINAL:CHARHEIGHT TO 16.
SET TERMINAL:HEIGHT TO 12.
COPYPATH("0:/LIB/FLIGHT_LIB.KS", "1:").
COPYPATH("0:/LIB/BASE_LIB.KS", "1:").
COPYPATH("0:/FLIGHT.KS", "1:").
BRAKES ON.

// MIGRATING AWAY TO DEFAULT BOOT SCRIPT AFTER
// CONSTELLATION OF SATELLITE COVERS ALL OF KERBIN
